apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: eso-metadata
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: external-secrets
  policyTypes: [Egress]
  egress:
    - to:
        - ipBlock:
            cidr: 169.254.169.254/32
      ports:
        - {protocol: TCP, port: 80}
