apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eps
  namespace: eps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: google-secrets
    kind: SecretStore
  target:
    name: eps
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: eps-app
      property: DATABASE_URL
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: eps-app
      property: POSTGRES_PASSWORD
  - secretKey: SECRET_KEY
    remoteRef:
      key: eps-app
      property: SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eps-db-admin
  namespace: eps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: google-secrets
    kind: SecretStore
  target:
    name: eps-db-admin
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: eps-db-admin
      property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eps-exporter
  namespace: eps
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: google-secrets
    kind: SecretStore
  target:
    name: eps-exporter
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: password
    remoteRef:
      key: eps-postgres-exporter
      property: password
  - secretKey: DATA_SOURCE_NAME
    remoteRef:
      key: eps-postgres-exporter
      property: DATA_SOURCE_NAME
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eps-grafana
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: google-secrets
    kind: SecretStore
  target:
    name: eps-grafana
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: admin-user
    remoteRef:
      key: eps-grafana
      property: admin-user
  - secretKey: admin-password
    remoteRef:
      key: eps-grafana
      property: admin-password
