apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eps-root-bootstrap
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eps-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: EPS private root CA
  secretName: eps-root-ca
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: eps-root-bootstrap
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  ca:
    secretName: eps-root-ca
