"""streak tables

Revision ID: 30a67166affa
Revises:
Create Date: 2026-08-01 18:40:51.767085

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30a67166affa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streaks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habit_log",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("streak_id", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["streak_id"],
            ["streaks.id"],
        ),
        sa.PrimaryKeyConstraint("date", "streak_id"),
    )
    op.create_table(
        "streak_state",
        sa.Column("streak_id", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("personal_record", sa.Integer(), nullable=False),
        sa.Column("last_grace_used_date", sa.Date(), nullable=True),
        sa.Column(
            "last_recomputed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["streak_id"],
            ["streaks.id"],
        ),
        sa.PrimaryKeyConstraint("streak_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("streak_state")
    op.drop_table("habit_log")
    op.drop_table("streaks")
    # ### end Alembic commands ###
