"""task time and ordering, tracker ordering, grace toggle

Revision ID: 857aac31eb81
Revises: ba0ca89ece9d
Create Date: 2026-08-02 13:51:59.301440

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "857aac31eb81"
down_revision: str | Sequence[str] | None = "ba0ca89ece9d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so the column can be added to a table that already has
    # rows; existing installs get grace on, matching previous behaviour
    op.add_column(
        "settings",
        sa.Column("grace_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column("tasks", sa.Column("scheduled_time", sa.Time(), nullable=True))
    op.add_column("tasks", sa.Column("sort_order", sa.Integer(), nullable=True))
    op.add_column("trackers", sa.Column("sort_order", sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trackers", "sort_order")
    op.drop_column("tasks", "sort_order")
    op.drop_column("tasks", "scheduled_time")
    op.drop_column("settings", "grace_enabled")
    # ### end Alembic commands ###
