"""remaining tables

Revision ID: ba0ca89ece9d
Revises: 30a67166affa
Create Date: 2026-08-01 19:22:04.745899

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba0ca89ece9d"
down_revision: str | Sequence[str] | None = "30a67166affa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar_cache",
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("all_day", sa.Boolean(), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index("idx_calendar_date", "calendar_cache", ["date"], unique=False)
    op.create_table(
        "daily_notes",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("note_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "daily_state",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("bad_day", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "edit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("table_name", sa.Text(), nullable=False),
        sa.Column("row_id", sa.Text(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("reason_optional", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metric_type", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("scale_min", sa.SmallInteger(), nullable=True),
        sa.Column("scale_max", sa.SmallInteger(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("metric_type IN ('scale', 'numeric')", name="metric_type_valid"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth_credentials",
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("connected_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_refreshed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False),
        sa.Column("calendar_fetch_time", sa.Time(), nullable=False),
        sa.Column("weather_fetch_time", sa.Time(), nullable=False),
        sa.Column("weather_location_lat", sa.Numeric(), nullable=False),
        sa.Column("weather_location_lon", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("id = 1", name="settings_single_row"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("scheduled_for", sa.Date(), nullable=True),
        sa.Column("vital", sa.Boolean(), nullable=False),
        sa.Column(
            "last_user_interaction_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("remind_after", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "deadline IS NOT NULL OR scheduled_for IS NOT NULL OR remind_after IS NOT NULL",
            name="task_has_temporal_context",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trackers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("threshold_days", sa.Integer(), nullable=False),
        sa.Column(
            "visible_on_days",
            sa.JSON().with_variant(postgresql.ARRAY(sa.SmallInteger()), "postgresql"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weather_cache",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "metric_log",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("metric_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["metric_id"],
            ["metrics.id"],
        ),
        sa.PrimaryKeyConstraint("date", "metric_id"),
    )
    op.create_table(
        "task_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "action IN ('created','completed','uncompleted','edited','snoozed','archived','unarchived')",
            name="task_event_action_valid",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracker_events",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("tracker_id", sa.Integer(), nullable=False),
        sa.Column("activity_done", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tracker_id"],
            ["trackers.id"],
        ),
        sa.PrimaryKeyConstraint("date", "tracker_id"),
    )
    op.create_table(
        "tracker_state",
        sa.Column("tracker_id", sa.Integer(), nullable=False),
        sa.Column("days_since_last_done", sa.Integer(), nullable=False),
        sa.Column("last_done_date", sa.Date(), nullable=True),
        sa.Column(
            "last_recomputed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tracker_id"],
            ["trackers.id"],
        ),
        sa.PrimaryKeyConstraint("tracker_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracker_state")
    op.drop_table("tracker_events")
    op.drop_table("task_events")
    op.drop_table("metric_log")
    op.drop_table("weather_cache")
    op.drop_table("trackers")
    op.drop_table("tasks")
    op.drop_table("settings")
    op.drop_table("oauth_credentials")
    op.drop_table("metrics")
    op.drop_table("edit_log")
    op.drop_table("daily_state")
    op.drop_table("daily_notes")
    op.drop_index("idx_calendar_date", table_name="calendar_cache")
    op.drop_table("calendar_cache")
    # ### end Alembic commands ###
