apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: eps-v04-dev
image: rancher/k3s:v1.36.3-k3s1
kubeAPI:
  hostIP: 127.0.0.1
  hostPort: "6550"
servers: 1
agents: 0
ports:
  - port: 127.0.0.1:8080:80
    nodeFilters: [loadbalancer]
  - port: 127.0.0.1:8443:443
    nodeFilters: [loadbalancer]
options:
  k3s:
    extraArgs:
      - arg: --secrets-encryption
        nodeFilters: ["server:*"]
