apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-eps-controller
  namespace: eps
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - events
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - services
  - configmaps
  verbs: &id001
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs: *id001
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs: *id001
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs: *id001
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs: *id001
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - prometheusrules
  verbs: *id001
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-eps-controller
  namespace: eps
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-eps-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-eps-reader
  namespace: eps
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - events
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - services
  - configmaps
  verbs: &id001
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs: *id001
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs: *id001
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs: *id001
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs: *id001
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - prometheusrules
  verbs: *id001
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-eps-reader
  namespace: eps
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-eps-reader
